const masters = [
    {
        name: "Анна Коваленко",
        photo: "/img/annaK.png",
        position: "Перукар",
        rating: 4.8,
        services: [
            { title: "Стрижка жіноча", price: 300, duration: 60 },
            { title: "Фарбування волосся", price: 500, duration: 120 },
            { title: "Укладка волосся", price: 200, duration: 45 },
            { title: "Кератинове випрямлення", price: 700, duration: 90 },
            { title: "Плетіння кіс", price: 250, duration: 50 },
            { title: "Нарощування волосся", price: 1000, duration: 180 },
            { title: "Вечірня зачіска", price: 400, duration: 75 },
            { title: "Маска для волосся", price: 150, duration: 30 },
        ],
    },
    {
        name: "Олександр Ткаченко",
        photo: "/img/oleksandrT.png",
        position: "Масажист",
        rating: 4.6,
        services: [
            { title: "Масаж обличчя", price: 400, duration: 45 },
            { title: "Антицелюлітний масаж", price: 600, duration: 60 },
            { title: "Релакс-масаж", price: 500, duration: 60 },
            { title: "Спортивний масаж", price: 700, duration: 75 },
            { title: "Лімфодренажний масаж", price: 650, duration: 70 },
            { title: "Масаж голови", price: 300, duration: 30 },
            { title: "Аромамасаж", price: 550, duration: 60 },
            { title: "Медовий масаж", price: 450, duration: 50 },
        ],
    },
    {
        name: "Марина Дорошенко",
        photo: "/img/marinaD.png",
        position: "Майстер манікюру",
        rating: 4.9,
        services: [
            { title: "Манікюр класичний", price: 250, duration: 60 },
            { title: "Педикюр апаратний", price: 400, duration: 90 },
            { title: "Нарощування нігтів", price: 600, duration: 120 },
            { title: "Дизайн нігтів", price: 350, duration: 75 },
            { title: "Зняття гель-лаку", price: 100, duration: 20 },
            { title: "Покриття гель-лаком", price: 300, duration: 45 },
            { title: "Парафінотерапія", price: 200, duration: 30 },
            { title: "Spa-манікюр", price: 400, duration: 75 },
        ],
    },
    {
        name: "Ірина Савченко",
        photo: "/img/irinaS.png",
        position: "Візажист",
        rating: 4.7,
        services: [
            { title: "Макіяж денний", price: 350, duration: 45 },
            { title: "Вечірній макіяж", price: 500, duration: 60 },
            { title: "Весільний макіяж", price: 800, duration: 90 },
            { title: "Корекція брів", price: 150, duration: 30 },
            { title: "Фарбування брів", price: 100, duration: 20 },
            { title: "Ламінування вій", price: 450, duration: 60 },
            { title: "Ламінування брів", price: 350, duration: 50 },
            { title: "Перманентний макіяж губ", price: 1200, duration: 120 },
        ],
    },
    {
        name: "Андрій Мельник",
        photo: "/img/andryiM.png",
        position: "Косметолог",
        rating: 4.5,
        services: [
            { title: "Догляд за обличчям", price: 500, duration: 60 },
            { title: "Чистка обличчя", price: 600, duration: 75 },
            { title: "Пілінг", price: 400, duration: 50 },
            { title: "Масаж обличчя", price: 350, duration: 45 },
            { title: "Антивіковий догляд", price: 700, duration: 90 },
            { title: "Маска для обличчя", price: 250, duration: 30 },
            { title: "Контурна пластика", price: 1200, duration: 120 },
            { title: "Мезотерапія", price: 800, duration: 60 },
            { title: "Ботокс", price: 1500, duration: 90 },
        ],
    },
    {
        name: "Катерина Іванова",
        photo: "/img/katerynaI.png",
        position: "Перукар",
        rating: 4.7,
        services: [
            { title: "Стрижка чоловіча", price: 250, duration: 45 },
            { title: "Фарбування волосся", price: 500, duration: 120 },
            { title: "Укладка волосся", price: 200, duration: 45 },
            { title: "Кератинове випрямлення", price: 700, duration: 90 },
            { title: "Ламінування волосся", price: 300, duration: 60 },
            { title: "Плетіння кіс", price: 250, duration: 50 },
            { title: "Зачіска на випускний", price: 450, duration: 75 },
            { title: "Вечірня зачіска", price: 400, duration: 75 },
        ],
    },
    {
        name: "Олексій Петров",
        photo: "/img/oleksiyP.png",
        position: "Масажист",
        rating: 4.5,
        services: [
            { title: "Масаж обличчя", price: 400, duration: 45 },
            { title: "Антицелюлітний масаж", price: 600, duration: 60 },
            { title: "Релакс-масаж", price: 500, duration: 60 },
            { title: "Масаж спини", price: 450, duration: 50 },
            { title: "Лімфодренажний масаж", price: 650, duration: 70 },
            { title: "Тайський масаж", price: 700, duration: 90 },
            { title: "Аромамасаж", price: 550, duration: 60 },
            { title: "Рефлексотерапія", price: 600, duration: 60 },
        ],
    },
    {
        name: "Вікторія Лисенко",
        photo: "/img/viktoriaL.png",
        position: "Майстер манікюру",
        rating: 4.6,
        services: [
            { title: "Манікюр класичний", price: 250, duration: 60 },
            { title: "Педикюр класичний", price: 350, duration: 70 },
            { title: "Нарощування нігтів", price: 600, duration: 120 },
            { title: "Дизайн нігтів", price: 350, duration: 75 },
            { title: "Покриття гель-лаком", price: 300, duration: 45 },
            { title: "Spa-манікюр", price: 400, duration: 75 },
            { title: "Парафінотерапія", price: 200, duration: 30 },
            { title: "Масаж рук", price: 150, duration: 20 },
        ],
    },
    {
        name: "Дмитро Сидоренко",
        photo: "/img/dmytroS.png",
        position: "Візажист",
        rating: 4.4,
        services: [
            { title: "Макіяж денний", price: 350, duration: 45 },
            { title: "Вечірній макіяж", price: 500, duration: 60 },
            { title: "Весільний макіяж", price: 800, duration: 90 },
            { title: "Корекція брів", price: 150, duration: 30 },
            { title: "Фарбування брів", price: 100, duration: 20 },
            { title: "Ламінування вій", price: 450, duration: 60 },
            { title: "Перманентний макіяж очей", price: 1000, duration: 90 },
            { title: "Перманентний макіяж брів", price: 1200, duration: 120 },
        ],
    },
    {
        name: "Тетяна Зайцева",
        photo: "/img/tetianaZ.png",
        position: "Перукар",
        rating: 4.6,
        services: [
            { title: "Стрижка жіноча", price: 300, duration: 60 },
            { title: "Стрижка чоловіча", price: 250, duration: 45 },
            { title: "Фарбування волосся", price: 500, duration: 120 },
            { title: "Укладка волосся", price: 200, duration: 45 },
            { title: "Кератинове випрямлення", price: 700, duration: 90 },
            { title: "Ламінування волосся", price: 300, duration: 60 },
            { title: "Плетіння кіс", price: 250, duration: 50 },
            { title: "Дитяча стрижка", price: 150, duration: 30 },
        ],
    },
];

export default masters;